name: SC-Build

on:
  workflow_call:
    inputs:
      solution:
        description: "Solution-fil som skal bygges"
        required: true
        type: string
      solution_path:
        description: "Path til solution (default: src)"
        required: false
        default: "src"
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: Restore
        run: dotnet restore ${{ inputs.solution_path }}/${{ inputs.solution }}

      - name: Build
        run: dotnet build ${{ inputs.solution_path }}/${{ inputs.solution }} --configuration Release --no-restore

      - name: Test
        run: dotnet test ${{ inputs.solution_path }}/${{ inputs.solution }} --configuration Release --no-build

      - name: Pack
        run: dotnet pack ${{ inputs.solution_path }}/${{ inputs.solution }} --configuration Release --no-build --output ./artifacts

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nuget-packages
          path: artifacts
